djangojokes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jokes/', include('jokes.urls')),
    path('', include('pages.urls')),
]

jokes/urls.py
from django.urls import path

app_name = 'jokes'
urlpatterns = []

pages/urls.py
from django.urls import path

from .views import AboutUsView, HomePageView

app_name = 'pages'
urlpatterns = [
   path('', HomePageView.as_view(), name='homepage'),
   path('about-us/', AboutUsView.as_view(), name='about-us'),
 ]

starter-code/template-filters-and-tags/urls.py
from django.urls import path

from .views import FilterView, HomePageView, TagView

urlpatterns = [
    path('', HomePageView.as_view(), name='homepage'),
    path('filters/', FilterView.as_view(), name='filters'),
    path('tags/', TagView.as_view(), name='tags'),
]

jokes/models.py
from django.db import models

# Create your models here.

starter-code/forms-and-widgets/forms.py
from datetime import datetime
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import URLValidator

def validate_future_date(value):
    if value < datetime.now().date():
        raise ValidationError(
            message=f'{value} is in the past.', code='past_date'
        )
    

class JobApplicationForm(forms.Form):
    EMPLOYMENT_TYPES = (
        (None, '--Please choose--'),
        ('ft', 'Full-time'),
        ('pt', 'Part-time'),
        ('contract', 'Contract work')
    )

    DAYS = (
        (1, 'MON'),
        (2, 'TUE'),
        (3, 'WED'),
        (4, 'THU'),
        (5, 'FRI')
    )
    
    YEARS = range(datetime.now().year, datetime.now().year+2)

    first_name = forms.CharField(
       widget=forms.TextInput(attrs={'autofocus': True})
    )
    last_name = forms.CharField()
    email = forms.EmailField()
    website = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder':'https://www.example.com', 'size':'50'}
        ),
        validators=[URLValidator(schemes=['http', 'https'])]
    )
    employment_type = forms.ChoiceField(choices=EMPLOYMENT_TYPES)
    start_date = forms.DateField(
        help_text='The earliest date you can start working.',
        widget=forms.SelectDateWidget(
            years=YEARS,
        ),
        validators=[validate_future_date],
        error_messages = {'past_date': 'Please enter a future date.'}
    )
    available_days = forms.TypedMultipleChoiceField(
        choices=DAYS,
        coerce=int,
        help_text='Check all days that you can work.',
        widget=forms.CheckboxSelectMultiple(
            attrs={'checked':True}
        )
    )
    desired_hourly_wage = forms.DecimalField(
        widget=forms.NumberInput(
            attrs={'min':'10.00', 'max':'100.00', 'step':'.25'}
        )
    )
    cover_letter = forms.CharField(
        widget=forms.Textarea(attrs={'cols': '75', 'rows': '5'})
    )
    confirmation = forms.BooleanField(
        label='I certify that the information I have provided is true.'
    )

jokes/views.py
from django.shortcuts import render

# Create your views here.

pages/views.py
from django.views.generic import TemplateView

class HomePageView(TemplateView):
 template_name = 'pages/home.html'


class AboutUsView(TemplateView):
  template_name ='pages/about_us.html'

starter-code/template-filters-and-tags/views.py
from django.views.generic import TemplateView

class FilterView(TemplateView):
    template_name = 'practice/filters.html'


class HomePageView(TemplateView):
    template_name = 'home.html'


class TagView(TemplateView):
    template_name = 'practice/tags.html'

templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- ADD BOOTSTRAP CSS FROM https://getbootstrap.com/ -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<!-- ADD FONT AWESOME FROM https://fontawesome.com/ --><
  script src="https://kit.fontawesome.com/ceae8f33b0.js" crossorigin="anonymous"></script>
<title>{% block title %}{% endblock %} | Djangojokes</title>
</head>
<body>
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'pages:homepage' %}">Djangojokes</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
      data-target="#navbarSupportedContent" aria-expanded="false"
      aria-controls="navbarSupportedContent" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'pages:homepage' %}">Home 
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Jokes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Log in</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" 
             role="button" data-toggle="dropdown" aria-haspopup="true"
             aria-expanded="false">
            Me
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">My Account</a>
            <a class="dropdown-item" href="#">My Djangojokes</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Log out</a>
          </div>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search"
        placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
          Search
        </button>
      </form>
    </div>
  </nav>
</header>
<main class="m-4 pb-5">
  {% block main %}<h2>Welcome!</h2>{% endblock %}
</main>
<footer class="fixed-bottom bg-light row">
    <div class="col">
      <div class="float-right m-1 mr-2">Copyright &copy; 2020 Djangojokes.</div>
      <nav>
        <ul class="nav">
          <li class="nav-item"><a class="nav-link" href="{% url 'pages:about-us' %}">About</a></li>
          <li class="nav-item"><a class="nav-link" href="#">Contact</a></li>
        </ul>
      </nav>
    </div>
  </nav>
</footer>
<!-- ADD BOOTSTRAP JS FROM https://getbootstrap.com/ -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

</body>
</html>

templates/pages/about_us.html
{% extends "_base.html" %}

{% block title %}About Us{% endblock %}
{% block main %}
 <h2>About Us</h2>
 <p>We tell funny jokes.</p>
{% endblock %}

templates/pages/home.html
{% extends "_base.html" %}

{% block title %}Home{% endblock %}
{% block main %}
 <h2>Welcome!</h2>
 <p>Ready to laugh?</p>
{% endblock %}